---
- name: "[Ahmed]"
  hosts: all
  tasks:
    - name: "[Ahmed] - git pull "
      git:
        repo: https://github.com/AK-SoloQ/mon-cv.git
        dest: /home/ahmed/mon-cv
        clone: no
        update: yes
    - name: "[Ahmed] - install docker & docker-compose "
      pip:
        name:
          - docker
          - docker-compose
    - name: Run `docker-compose up` again
      docker_compose:
        project_src: /home/ahmed/mon-cv
        files: docker-compose-prod.yml
        build: yes
        restarted: yes
